version: '3.8'

services:
  back:
    build: src
    ports:
      - 8000:8000
  front:
    build: .
    ports:
      - 7861:7861
    depends_on:
      - back
  whisper:
    build: src/models/whisper
    ports:
      - 8001:8001
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

# version: '3.8'

# services:
#   fastapi:
#     build: src
#     ports:
#       - 8000:8000
#     deploy:
#       resources:
#         reservations:
#           devices:
#             - driver: nvidia
#               count: 1
#               capabilities: [gpu]
#   front:
#     build: .
#     ports:
#       - 7861:7861
#     depends_on:
#       - fastapi